### ISSUE TITLE
Would you please also provide random mask ckpt?

### ISSUE THREAD

**Issue by juxuan27** [kijai/ComfyUI-BrushNet-Wrapper#10]
Hi, thank you for your effort in supporting BrushNet in ComfyUI!
Would you please also support the random mask ckpt in downloading so that it can be used with masks with random shape? The ckpt is here: https://drive.google.com/drive/folders/1hCYIjeRGx3Zk9WZtQf0s3nDGfeiwqTsN .

**Comment by kijai** [comment]
Hey, thank you for the excellent inpainting method and model! The model loader has had the option to choose this from the beginning though! 
![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/40791699/0443b18a-b8cd-4948-af27-14e601688d65)

**Comment by juxuan27** [comment]
Oh! Thank you for clarifying!
