### ISSUE TITLE
any plan to support official ella?

### ISSUE THREAD

**Issue by DENG-XC** [kijai/ComfyUI-BrushNet-Wrapper#17]
Hi, thanks for your hard work!
will you upgrade the node to support official ella in the future？
https://github.com/TencentQQGYLab/ComfyUI-ELLA.git

**Comment by kijai** [comment]
It is already using their official code, just the diffusers version like BrushNet itself with these wrapper nodes. The optimal thing would be to implement BrushNet natively in Comfy, I'm hoping Tencent will also do that as they now have done with ELLA, both being their models and code.
