### ISSUE TITLE
Ipadapter Stays Cached in the Brushnet Sampler

### ISSUE THREAD

**Issue by Beamhi** [kijai/ComfyUI-BrushNet-Wrapper#2]
Regardless of whether or not I bypass the ipadapter node, I still get the same result I got with the ipadapter.

**Comment by kijai** [comment]
Yeah I'm actually aware, just didn't get around to unloading it. Changing model will reset it for now, I'll look into it.

**Comment by Beamhi** [comment]
Thanks for all your efforts!! I notices because I usually like to test the effects of ip.

**Comment by kijai** [comment]
> Thanks for all your efforts!! I notices because I usually like to test the effects of ip.

I had to change up the layout a bit to do this properly (with my limited knowledge at least), but it works, you'll have to recreate the IPAdapter node after updating though, refresh should be enough to add the input to the model loader, if not recreate it as well.

![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/40791699/fead4d0f-4fb7-43fa-8273-71cb429bc2f3)

**Comment by Beamhi** [comment]
limited knowledge? quite humble!! thanks to you, we have so many essential nodes. 
will update now and test.
