### ISSUE TITLE
Incompatible with differusers==0.28.0

### ISSUE THREAD

**Issue by HelloClyde** [kijai/ComfyUI-BrushNet-Wrapper#30]
When updating to differusers==0.28.0, due to the break change in differusers, the import of create_vae_diffusers_config by brushnet nodes fails.
`
.Traceback (most recent call last):
  File "/root/comfyui/custom_nodes/ComfyUI-BrushNet-Wrapper/nodes.py", line 18, in <module>
    from diffusers.loaders.single_file_utils import (
ImportError: cannot import name 'create_vae_diffusers_config' from 'diffusers.loaders.single_file_utils' (/opt/conda/lib/python3.10/site-packages/diffusers/loaders/single_file_utils.py)

During handling of the above exception, another exception occurred:`

https://github.com/huggingface/diffusers/commit/cb0f3b49cbd9f67c088a8cd8e96e477a6ae47764#diff-46dbaee212aec178869ccc3db97f026579819d5fbffbd4321e7063cf472139f8

**Comment by kijai** [comment]
Fixed this now, but I don't really plan to support the wrapper and recommend using the comfyui native version: https://github.com/nullquant/ComfyUI-BrushNet
