### ISSUE TITLE
Does BrushNet Model Loader upport SDXL models?

### ISSUE THREAD

**Issue by VichyTong** [kijai/ComfyUI-BrushNet-Wrapper#31]
Hi,

Thank you for your great job. I have tried some SD 1.5-type base models and they worked perfectly. However, when I changed the model to SDXL-type, it throws an error.

<img width="627" alt="0ce8a27c9f556881ee8d17b611326d1" src="https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/91675945/9e03a928-f2e4-4626-b041-372c0cd5650a">
<img width="1026" alt="48a90fdcfaa4cffbd11ccd0a13b2580" src="https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/91675945/1a9f39d9-efe4-470c-a7c1-613546afb939">

Does the node support SDXL models or did I load it incorrectly?
I appreciate your help in advance.

Best,
Weixi

**Comment by kijai** [comment]
Hey,

I would recommend moving on to using these nodes for Brushnet instead, as they are more native implementation, and supports the SDXL model as well. I probably won't be updating this wrapper anymore:

https://github.com/nullquant/ComfyUI-BrushNet

**Comment by VichyTong** [comment]
Hi kijai,

Thank you so much! I will try these nodes.
