### ISSUE TITLE
Does it only work with SD1.5? I get an error when I'm using the SDXL model

### ISSUE THREAD

**Issue by Fred10086** [kijai/ComfyUI-BrushNet-Wrapper#4]
![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/166596625/9cc2e640-25d1-4351-9520-e8922780df96)
I get this error when I'm using the XL model

**Comment by kijai** [comment]
Yeah only 1.5 for now, they have not released SDXL version.
