### ISSUE TITLE
How to pass parameters,Please Help

### ISSUE THREAD

**Issue by sswink** [kijai/ComfyUI-BrushNet-Wrapper#9]
Thanks for your awesome comfyui nodes,I tried it several times, but it didn't work like it did on huggingface. Did the parameters get passed wrong. please Help

https://huggingface.co/spaces/TencentARC/BrushNet

![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/30194825/36800226-2d27-4ff0-a374-4760498a0ffd)

![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/30194825/0b54e6f3-8ed4-4b0e-a486-6771ce1ea71d)

**Comment by sswink** [comment]
I tried many times, but the results were not good
![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/30194825/35ce2b9e-20be-4cc3-b21d-1bcb109bea34)
Here is my image and workflow, can you please look and help,Thank you so much
![1713102796181QdlRV1](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/30194825/26e70ca8-9223-4668-b11e-9424bc973a79)
![ComfyUI_temp_mgkfu_00003_](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/30194825/89cb65d0-57d9-4048-8cd8-9aca1a98c74c)
[clothes.json](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/files/14999535/clothes.json)

**Comment by kijai** [comment]
Seems to work fine for me:
![image](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/assets/40791699/0e168e2d-7618-4496-ade9-5c715c9d0dde)
[brushnet_clothes_test.json](https://github.com/kijai/ComfyUI-BrushNet-Wrapper/files/15012053/brushnet_clothes_test.json)
